site_name: SkyGuardian Docs
site_description: "Documentation for the SkyGuardian project"
site_author: "Your Name or Team"

# Where your markdown files live
docs_dir: docs

# Theme configuration (using Material for MkDocs)
theme:
  name: material
  palette:
    primary: indigo
    accent: blue
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - content.code.copy

# Navigation structure
nav:
  - Home: index.md
  - Project Charter: project_charter.md
  - Getting Started: getting_started.md
  - Development:
      - Architecture: architecture.md
      - Rules of Engagement: roe.md

# Enable search plugin
plugins:
  - search  # Make sure a `docs/` directory with markdown files exists in the repo

# Markdown extensions (optional)
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - tables

# Extra configuration (optional)
# extra_css:
#   - stylesheets/extra.css
# extra_javascript:
#   - javascripts/extra.js 